/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as FerramentaParaAchadinhosRouteImport } from './routes/ferramenta-para-achadinhos'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AchadinhosIndexRouteImport } from './routes/achadinhos.index'
import { Route as AchadinhosLojaRouteImport } from './routes/achadinhos.$loja'
import { Route as AfiliadosLojaRouteImport } from './routes/afiliados.$loja'
import { Route as ComparativosVupiaVsEnvioManualRouteImport } from './routes/comparativos.vupia-vs-envio-manual'
import { Route as FerramentasGeradorDeMensagemRouteImport } from './routes/ferramentas.gerador-de-mensagem'
import { Route as FuncionalidadesAutomacaoDeGruposRouteImport } from './routes/funcionalidades/automacao-de-grupos'
import { Route as FuncionalidadesGruposDeOfertasRouteImport } from './routes/funcionalidades/grupos-de-ofertas'
import { Route as FuncionalidadesWhatsappParaAfiliadosRouteImport } from './routes/funcionalidades/whatsapp-para-afiliados'
import { Route as GuiasIndexRouteImport } from './routes/guias.index'
import { Route as GuiasSlugRouteImport } from './routes/guias.$slug'
import { Route as ProgramaDeAfiliadosIndexRouteImport } from './routes/programa-de-afiliados.index'
import { Route as ProgramaDeAfiliadosEmbaixadoresRouteImport } from './routes/programa-de-afiliados/embaixadores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentaParaAchadinhosRoute =
  FerramentaParaAchadinhosRouteImport.update({
    id: '/ferramenta-para-achadinhos',
    path: '/ferramenta-para-achadinhos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AchadinhosIndexRoute = AchadinhosIndexRouteImport.update({
  id: '/achadinhos/',
  path: '/achadinhos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchadinhosLojaRoute = AchadinhosLojaRouteImport.update({
  id: '/achadinhos/$loja',
  path: '/achadinhos/$loja',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosLojaRoute = AfiliadosLojaRouteImport.update({
  id: '/afiliados/$loja',
  path: '/afiliados/$loja',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativosVupiaVsEnvioManualRoute =
  ComparativosVupiaVsEnvioManualRouteImport.update({
    id: '/comparativos/vupia-vs-envio-manual',
    path: '/comparativos/vupia-vs-envio-manual',
    getParentRoute: () => rootRouteImport,
  } as any)
const FerramentasGeradorDeMensagemRoute =
  FerramentasGeradorDeMensagemRouteImport.update({
    id: '/ferramentas/gerador-de-mensagem',
    path: '/ferramentas/gerador-de-mensagem',
    getParentRoute: () => rootRouteImport,
  } as any)
const FuncionalidadesAutomacaoDeGruposRoute =
  FuncionalidadesAutomacaoDeGruposRouteImport.update({
    id: '/funcionalidades/automacao-de-grupos',
    path: '/funcionalidades/automacao-de-grupos',
    getParentRoute: () => rootRouteImport,
  } as any)
const FuncionalidadesGruposDeOfertasRoute =
  FuncionalidadesGruposDeOfertasRouteImport.update({
    id: '/funcionalidades/grupos-de-ofertas',
    path: '/funcionalidades/grupos-de-ofertas',
    getParentRoute: () => rootRouteImport,
  } as any)
const FuncionalidadesWhatsappParaAfiliadosRoute =
  FuncionalidadesWhatsappParaAfiliadosRouteImport.update({
    id: '/funcionalidades/whatsapp-para-afiliados',
    path: '/funcionalidades/whatsapp-para-afiliados',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiasIndexRoute = GuiasIndexRouteImport.update({
  id: '/guias/',
  path: '/guias/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasSlugRoute = GuiasSlugRouteImport.update({
  id: '/guias/$slug',
  path: '/guias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramaDeAfiliadosIndexRoute =
  ProgramaDeAfiliadosIndexRouteImport.update({
    id: '/programa-de-afiliados/',
    path: '/programa-de-afiliados/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramaDeAfiliadosEmbaixadoresRoute =
  ProgramaDeAfiliadosEmbaixadoresRouteImport.update({
    id: '/programa-de-afiliados/embaixadores',
    path: '/programa-de-afiliados/embaixadores',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/ferramenta-para-achadinhos': typeof FerramentaParaAchadinhosRoute
  '/programas': typeof ProgramasRoute
  '/sobre': typeof SobreRoute
  '/achadinhos/$loja': typeof AchadinhosLojaRoute
  '/afiliados/$loja': typeof AfiliadosLojaRoute
  '/comparativos/vupia-vs-envio-manual': typeof ComparativosVupiaVsEnvioManualRoute
  '/ferramentas/gerador-de-mensagem': typeof FerramentasGeradorDeMensagemRoute
  '/funcionalidades/automacao-de-grupos': typeof FuncionalidadesAutomacaoDeGruposRoute
  '/funcionalidades/grupos-de-ofertas': typeof FuncionalidadesGruposDeOfertasRoute
  '/funcionalidades/whatsapp-para-afiliados': typeof FuncionalidadesWhatsappParaAfiliadosRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/programa-de-afiliados/embaixadores': typeof ProgramaDeAfiliadosEmbaixadoresRoute
  '/achadinhos/': typeof AchadinhosIndexRoute
  '/guias/': typeof GuiasIndexRoute
  '/programa-de-afiliados/': typeof ProgramaDeAfiliadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/ferramenta-para-achadinhos': typeof FerramentaParaAchadinhosRoute
  '/programas': typeof ProgramasRoute
  '/sobre': typeof SobreRoute
  '/achadinhos/$loja': typeof AchadinhosLojaRoute
  '/afiliados/$loja': typeof AfiliadosLojaRoute
  '/comparativos/vupia-vs-envio-manual': typeof ComparativosVupiaVsEnvioManualRoute
  '/ferramentas/gerador-de-mensagem': typeof FerramentasGeradorDeMensagemRoute
  '/funcionalidades/automacao-de-grupos': typeof FuncionalidadesAutomacaoDeGruposRoute
  '/funcionalidades/grupos-de-ofertas': typeof FuncionalidadesGruposDeOfertasRoute
  '/funcionalidades/whatsapp-para-afiliados': typeof FuncionalidadesWhatsappParaAfiliadosRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/programa-de-afiliados/embaixadores': typeof ProgramaDeAfiliadosEmbaixadoresRoute
  '/achadinhos': typeof AchadinhosIndexRoute
  '/guias': typeof GuiasIndexRoute
  '/programa-de-afiliados': typeof ProgramaDeAfiliadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/ferramenta-para-achadinhos': typeof FerramentaParaAchadinhosRoute
  '/programas': typeof ProgramasRoute
  '/sobre': typeof SobreRoute
  '/achadinhos/$loja': typeof AchadinhosLojaRoute
  '/afiliados/$loja': typeof AfiliadosLojaRoute
  '/comparativos/vupia-vs-envio-manual': typeof ComparativosVupiaVsEnvioManualRoute
  '/ferramentas/gerador-de-mensagem': typeof FerramentasGeradorDeMensagemRoute
  '/funcionalidades/automacao-de-grupos': typeof FuncionalidadesAutomacaoDeGruposRoute
  '/funcionalidades/grupos-de-ofertas': typeof FuncionalidadesGruposDeOfertasRoute
  '/funcionalidades/whatsapp-para-afiliados': typeof FuncionalidadesWhatsappParaAfiliadosRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/programa-de-afiliados/embaixadores': typeof ProgramaDeAfiliadosEmbaixadoresRoute
  '/achadinhos/': typeof AchadinhosIndexRoute
  '/guias/': typeof GuiasIndexRoute
  '/programa-de-afiliados/': typeof ProgramaDeAfiliadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/ferramenta-para-achadinhos'
    | '/programas'
    | '/sobre'
    | '/achadinhos/$loja'
    | '/afiliados/$loja'
    | '/comparativos/vupia-vs-envio-manual'
    | '/ferramentas/gerador-de-mensagem'
    | '/funcionalidades/automacao-de-grupos'
    | '/funcionalidades/grupos-de-ofertas'
    | '/funcionalidades/whatsapp-para-afiliados'
    | '/guias/$slug'
    | '/programa-de-afiliados/embaixadores'
    | '/achadinhos/'
    | '/guias/'
    | '/programa-de-afiliados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/ferramenta-para-achadinhos'
    | '/programas'
    | '/sobre'
    | '/achadinhos/$loja'
    | '/afiliados/$loja'
    | '/comparativos/vupia-vs-envio-manual'
    | '/ferramentas/gerador-de-mensagem'
    | '/funcionalidades/automacao-de-grupos'
    | '/funcionalidades/grupos-de-ofertas'
    | '/funcionalidades/whatsapp-para-afiliados'
    | '/guias/$slug'
    | '/programa-de-afiliados/embaixadores'
    | '/achadinhos'
    | '/guias'
    | '/programa-de-afiliados'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/ferramenta-para-achadinhos'
    | '/programas'
    | '/sobre'
    | '/achadinhos/$loja'
    | '/afiliados/$loja'
    | '/comparativos/vupia-vs-envio-manual'
    | '/ferramentas/gerador-de-mensagem'
    | '/funcionalidades/automacao-de-grupos'
    | '/funcionalidades/grupos-de-ofertas'
    | '/funcionalidades/whatsapp-para-afiliados'
    | '/guias/$slug'
    | '/programa-de-afiliados/embaixadores'
    | '/achadinhos/'
    | '/guias/'
    | '/programa-de-afiliados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  FerramentaParaAchadinhosRoute: typeof FerramentaParaAchadinhosRoute
  ProgramasRoute: typeof ProgramasRoute
  SobreRoute: typeof SobreRoute
  AchadinhosLojaRoute: typeof AchadinhosLojaRoute
  AfiliadosLojaRoute: typeof AfiliadosLojaRoute
  ComparativosVupiaVsEnvioManualRoute: typeof ComparativosVupiaVsEnvioManualRoute
  FerramentasGeradorDeMensagemRoute: typeof FerramentasGeradorDeMensagemRoute
  FuncionalidadesAutomacaoDeGruposRoute: typeof FuncionalidadesAutomacaoDeGruposRoute
  FuncionalidadesGruposDeOfertasRoute: typeof FuncionalidadesGruposDeOfertasRoute
  FuncionalidadesWhatsappParaAfiliadosRoute: typeof FuncionalidadesWhatsappParaAfiliadosRoute
  GuiasSlugRoute: typeof GuiasSlugRoute
  ProgramaDeAfiliadosEmbaixadoresRoute: typeof ProgramaDeAfiliadosEmbaixadoresRoute
  AchadinhosIndexRoute: typeof AchadinhosIndexRoute
  GuiasIndexRoute: typeof GuiasIndexRoute
  ProgramaDeAfiliadosIndexRoute: typeof ProgramaDeAfiliadosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramenta-para-achadinhos': {
      id: '/ferramenta-para-achadinhos'
      path: '/ferramenta-para-achadinhos'
      fullPath: '/ferramenta-para-achadinhos'
      preLoaderRoute: typeof FerramentaParaAchadinhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achadinhos/': {
      id: '/achadinhos/'
      path: '/achadinhos'
      fullPath: '/achadinhos/'
      preLoaderRoute: typeof AchadinhosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achadinhos/$loja': {
      id: '/achadinhos/$loja'
      path: '/achadinhos/$loja'
      fullPath: '/achadinhos/$loja'
      preLoaderRoute: typeof AchadinhosLojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados/$loja': {
      id: '/afiliados/$loja'
      path: '/afiliados/$loja'
      fullPath: '/afiliados/$loja'
      preLoaderRoute: typeof AfiliadosLojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativos/vupia-vs-envio-manual': {
      id: '/comparativos/vupia-vs-envio-manual'
      path: '/comparativos/vupia-vs-envio-manual'
      fullPath: '/comparativos/vupia-vs-envio-manual'
      preLoaderRoute: typeof ComparativosVupiaVsEnvioManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/gerador-de-mensagem': {
      id: '/ferramentas/gerador-de-mensagem'
      path: '/ferramentas/gerador-de-mensagem'
      fullPath: '/ferramentas/gerador-de-mensagem'
      preLoaderRoute: typeof FerramentasGeradorDeMensagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionalidades/automacao-de-grupos': {
      id: '/funcionalidades/automacao-de-grupos'
      path: '/funcionalidades/automacao-de-grupos'
      fullPath: '/funcionalidades/automacao-de-grupos'
      preLoaderRoute: typeof FuncionalidadesAutomacaoDeGruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionalidades/grupos-de-ofertas': {
      id: '/funcionalidades/grupos-de-ofertas'
      path: '/funcionalidades/grupos-de-ofertas'
      fullPath: '/funcionalidades/grupos-de-ofertas'
      preLoaderRoute: typeof FuncionalidadesGruposDeOfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionalidades/whatsapp-para-afiliados': {
      id: '/funcionalidades/whatsapp-para-afiliados'
      path: '/funcionalidades/whatsapp-para-afiliados'
      fullPath: '/funcionalidades/whatsapp-para-afiliados'
      preLoaderRoute: typeof FuncionalidadesWhatsappParaAfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/': {
      id: '/guias/'
      path: '/guias'
      fullPath: '/guias/'
      preLoaderRoute: typeof GuiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/$slug': {
      id: '/guias/$slug'
      path: '/guias/$slug'
      fullPath: '/guias/$slug'
      preLoaderRoute: typeof GuiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa-de-afiliados/': {
      id: '/programa-de-afiliados/'
      path: '/programa-de-afiliados'
      fullPath: '/programa-de-afiliados/'
      preLoaderRoute: typeof ProgramaDeAfiliadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programa-de-afiliados/embaixadores': {
      id: '/programa-de-afiliados/embaixadores'
      path: '/programa-de-afiliados/embaixadores'
      fullPath: '/programa-de-afiliados/embaixadores'
      preLoaderRoute: typeof ProgramaDeAfiliadosEmbaixadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  FerramentaParaAchadinhosRoute: FerramentaParaAchadinhosRoute,
  ProgramasRoute: ProgramasRoute,
  SobreRoute: SobreRoute,
  AchadinhosLojaRoute: AchadinhosLojaRoute,
  AfiliadosLojaRoute: AfiliadosLojaRoute,
  ComparativosVupiaVsEnvioManualRoute: ComparativosVupiaVsEnvioManualRoute,
  FerramentasGeradorDeMensagemRoute: FerramentasGeradorDeMensagemRoute,
  FuncionalidadesAutomacaoDeGruposRoute: FuncionalidadesAutomacaoDeGruposRoute,
  FuncionalidadesGruposDeOfertasRoute: FuncionalidadesGruposDeOfertasRoute,
  FuncionalidadesWhatsappParaAfiliadosRoute:
    FuncionalidadesWhatsappParaAfiliadosRoute,
  GuiasSlugRoute: GuiasSlugRoute,
  ProgramaDeAfiliadosEmbaixadoresRoute: ProgramaDeAfiliadosEmbaixadoresRoute,
  AchadinhosIndexRoute: AchadinhosIndexRoute,
  GuiasIndexRoute: GuiasIndexRoute,
  ProgramaDeAfiliadosIndexRoute: ProgramaDeAfiliadosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
